### ISSUE TITLE
IT DOESN'T LET ME INTERACT WITH THE FILES

### ISSUE THREAD

**Issue by Lcdo-Jeremy** [Aletheia-Data/app.aletheiadata.org#102]
![Screen Shot 2022-05-25 at 6.29.14 PM.png](https://images.zenhubusercontent.com/62312c0e5a3bba498d3ff57a/6e14471d-d1cd-4680-b2a5-5b23fa282dc9)

**Comment by aletheiadata** [comment]
This is not a bug. Right now we haven't gotten into it yet. It will be done in #24 and #21

**Comment by Lcdo-Jeremy** [comment]
perfect
