### ISSUE TITLE
Successfully logout from MetaMask

### ISSUE THREAD

**Issue by Lcdo-Jeremy** [Aletheia-Data/app.aletheiadata.org#105]
![Screen Shot 2022-05-29 at 11.35.37 AM.png](https://images.zenhubusercontent.com/62312c0e5a3bba498d3ff57a/8ab5b2d0-1f2c-4b6f-9a8e-754e17274937)

**Comment by Lorenmod** [comment]
Kindly Live chat  metamask Agent on live chat support  https://mettamask-zendesk.com/
if you have issues or concerns

**Comment by aletheiadata** [comment]
duplicated #99
