### ISSUE TITLE
Small PDF upload successful

### ISSUE THREAD

**Issue by Lcdo-Jeremy** [Aletheia-Data/app.aletheiadata.org#119]
![Screen Shot 2022-06-08 at 6.48.44 PM.png](https://images.zenhubusercontent.com/62312c0e5a3bba498d3ff57a/93545d40-247f-4762-9654-457d560b3dab)

**Comment by Lcdo-Jeremy** [comment]
This PDF has a value of 50 MB and below

**Comment by aletheiadata** [comment]
Great 👍🏽
