### ISSUE TITLE
SEARCH - finish Search component (categories and items)

### ISSUE THREAD

**Issue by aletheiadata** [Aletheia-Data/app.aletheiadata.org#36]
**Is your feature request related to a problem? Please describe.**
Finishing the last features in the search component and fix some bug/limitations.

- [x] when you open the modal, we see the wrong message. Add a message if you haven't search anything yet

<img width="629" alt="Screen Shot 2022-05-16 at 6 30 38 PM" src="https://user-images.githubusercontent.com/88608718/168693068-007f9386-8f6d-46ee-a6e9-80152f776a92.png">

- [x] add links to categories
- [x] add covers (image) to categories
- [x] remove `tutorials` and add 'last uploads' with 5 results (get query from `utils/queries`)
- [x] find a way to improve on the limitation in mongodb regarding 'case sensitive' search

**Comment by natachadelarosa** [comment]
@aletheiadata  We need to update rapid api `assets` endpoint so it allow us to search by userAddress

**Comment by aletheiadata** [comment]
> * @aletheiadata  We need to update rapid api `assets` endpoint so it allow us to search by
> * Also upload each category image
> * userAddress

added new parameter `wallet_address` under `[GET metadata](https://rapidapi.com/aletheia-data-aletheia-data-default/api/aletheia2)` endpoint. Now you can pass the user's wallet to this call to get their latest assets' uploads.

**Comment by natachadelarosa** [comment]
Also check PR: https://github.com/Aletheia-Data/api.aletheiadata.org/pull/59
