### ISSUE TITLE
El link al documento luego de subir un archivo no es el correcto

### ISSUE THREAD

**Issue by natachadelarosa** [Aletheia-Data/app.aletheiadata.org#89]

**Comment by natachadelarosa** [comment]
El link que muestra es incorrecto:
![image.png](https://images.zenhubusercontent.com/62268712d5e854edf13cf59a/035302d9-9f1c-4d91-b547-21292a152af1)

Al seguirlo no presenta una pantalla en blanco:
![image.png](https://images.zenhubusercontent.com/62268712d5e854edf13cf59a/18e0e9d3-60af-4052-aae1-533dd543c165)

**Comment by aletheiadata** [comment]
@natachadelarosa please title this in english. Also, can you please retry. I made a fix on the api for this. Please try with the same asset.

**Comment by aletheiadata** [comment]
this is because the upload failed, probably due to file size. Closed for now
