### ISSUE TITLE
Logout not working

### ISSUE THREAD

**Issue by Lcdo-Jeremy** [Aletheia-Data/app.aletheiadata.org#99]
We need to make sure the app logs you out if you disconnect from metamask

**Comment by aletheiadata** [comment]
also make sure disconnecting with metamask works

![Screen Shot 2022-05-27 at 6.55.40 AM.png](https://images.zenhubusercontent.com/620906acfa23f12500cc2add/448b9789-94c2-45c3-9807-e690c227bf49)

**Comment by aletheiadata** [comment]
not necessary after #33
